# General Jekyll Settings
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
markdown: kramdown
gems: [jekyll-paginate, jekyll-sitemap]
paginate: 5
excerpt_separator: <!--more-->
permalink: "/:year/:month/:day/:title"  

# Site settings
title: JonTheNerd
email: jon.badgett@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Jon Badgett's personal blog. Open Source projects, observations on life, 
  and other oddities that I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jonthenerd.com" # the base hostname & protocol for your site
gh-pages-url: "https://github.com/jonthenerd/jonthenerd.github.io"
twitter_username: jonthenerd
github_username:  jonthenerd
fb_profileurl: "https://www.facebook.com/jon.badgett.5"
gh_profileurl: "https://github.com/jonthenerd"
li_profileurl: "https://www.linkedin.com/in/jon-badgett-825a326b"
gp_profileurl: "https://plus.google.com/+JonBadgett"
tw_profileurl: "https://twitter.com/jonthenerd"
author: Jon Badgett

# defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts


