baseURL: "http://www.jonthenerd.com/"
languageCode: "en-us"
title: "JonTheNerd"

params:
    repoOrigin: https://github.com/jonthenerd/jonthenerd.github.io

permalinks:
    posts: /:year/:month/:day/:slug/

outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "feed"

outputs:
    home:
        - HTML
        - RSS

pygmentsUseClasses: true
enableEmoji: true

markup:
    goldmark:
        parser:
            attribute:
                block: true
